/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'

const NewAccountFormLazyRouteImport = createFileRoute('/newAccountForm')()
const AccountListLazyRouteImport = createFileRoute('/accountList')()
const AccountInfoAccountIdLazyRouteImport = createFileRoute(
  '/accountInfo/$accountId',
)()

const NewAccountFormLazyRoute = NewAccountFormLazyRouteImport.update({
  id: '/newAccountForm',
  path: '/newAccountForm',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/newAccountForm.lazy').then((d) => d.Route),
)
const AccountListLazyRoute = AccountListLazyRouteImport.update({
  id: '/accountList',
  path: '/accountList',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/accountList.lazy').then((d) => d.Route))
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountInfoAccountIdLazyRoute =
  AccountInfoAccountIdLazyRouteImport.update({
    id: '/accountInfo/$accountId',
    path: '/accountInfo/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/accountInfo/$accountId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/accountList': typeof AccountListLazyRoute
  '/newAccountForm': typeof NewAccountFormLazyRoute
  '/accountInfo/$accountId': typeof AccountInfoAccountIdLazyRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/accountList': typeof AccountListLazyRoute
  '/newAccountForm': typeof NewAccountFormLazyRoute
  '/accountInfo/$accountId': typeof AccountInfoAccountIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRoute
  '/accountList': typeof AccountListLazyRoute
  '/newAccountForm': typeof NewAccountFormLazyRoute
  '/accountInfo/$accountId': typeof AccountInfoAccountIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/accountList'
    | '/newAccountForm'
    | '/accountInfo/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/accountList' | '/newAccountForm' | '/accountInfo/$accountId'
  id:
    | '__root__'
    | '/home'
    | '/accountList'
    | '/newAccountForm'
    | '/accountInfo/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  AccountListLazyRoute: typeof AccountListLazyRoute
  NewAccountFormLazyRoute: typeof NewAccountFormLazyRoute
  AccountInfoAccountIdLazyRoute: typeof AccountInfoAccountIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newAccountForm': {
      id: '/newAccountForm'
      path: '/newAccountForm'
      fullPath: '/newAccountForm'
      preLoaderRoute: typeof NewAccountFormLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountList': {
      id: '/accountList'
      path: '/accountList'
      fullPath: '/accountList'
      preLoaderRoute: typeof AccountListLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountInfo/$accountId': {
      id: '/accountInfo/$accountId'
      path: '/accountInfo/$accountId'
      fullPath: '/accountInfo/$accountId'
      preLoaderRoute: typeof AccountInfoAccountIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  AccountListLazyRoute: AccountListLazyRoute,
  NewAccountFormLazyRoute: NewAccountFormLazyRoute,
  AccountInfoAccountIdLazyRoute: AccountInfoAccountIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
