/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'

const AccountListLazyRouteImport = createFileRoute('/accountList')()
const AccountInfoLazyRouteImport = createFileRoute('/accountInfo')()

const AccountListLazyRoute = AccountListLazyRouteImport.update({
  id: '/accountList',
  path: '/accountList',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/accountList.lazy').then((d) => d.Route))
const AccountInfoLazyRoute = AccountInfoLazyRouteImport.update({
  id: '/accountInfo',
  path: '/accountInfo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/accountInfo.lazy').then((d) => d.Route))
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/accountInfo': typeof AccountInfoLazyRoute
  '/accountList': typeof AccountListLazyRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/accountInfo': typeof AccountInfoLazyRoute
  '/accountList': typeof AccountListLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRoute
  '/accountInfo': typeof AccountInfoLazyRoute
  '/accountList': typeof AccountListLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/accountInfo' | '/accountList'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/accountInfo' | '/accountList'
  id: '__root__' | '/home' | '/accountInfo' | '/accountList'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  AccountInfoLazyRoute: typeof AccountInfoLazyRoute
  AccountListLazyRoute: typeof AccountListLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accountList': {
      id: '/accountList'
      path: '/accountList'
      fullPath: '/accountList'
      preLoaderRoute: typeof AccountListLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountInfo': {
      id: '/accountInfo'
      path: '/accountInfo'
      fullPath: '/accountInfo'
      preLoaderRoute: typeof AccountInfoLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  AccountInfoLazyRoute: AccountInfoLazyRoute,
  AccountListLazyRoute: AccountListLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
